name: time_calculator
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #BASE
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_portal: ^1.1.3
  firebase_storage: ^11.2.1
  pin_code_fields: ^7.4.0
  flutter_native_splash: ^2.2.19
  native_device_orientation: ^1.1.4
  connectivity_plus: ^4.0.1
  device_orientation: ^0.0.1
  flutter_launcher_icons: "^0.13.1"

  #Responsive screen UI
  sizer: ^2.0.15

  #Getx & Dependency Management
  get: ^4.6.5
  get_it: ^7.6.0

  #SVG images
  flutter_svg: ^2.0.5

  #Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

  #Flutter generator
  flutter_gen: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1

flutter_launcher_icons:
  image_path: "assets/icons/ic_time.png"
  web:
    generate: true
    image_path: "assets/icons/ic_time.png"
    background_color: "#ffffff"

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/values/colors.xml

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/values/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
